import type { publicationFor } from './publication.js';
import { escapeHTML as esc, reviewLabel } from './presentation.js';
import { withBase, canonicalURL } from './urls.js';
import { exportPath, rawPath, publicationCredit, citationGates, publicationAssets } from './publication-assets.js';
import type { Entry } from './content-schema.js';
import type { SiteConfig } from './site-config.js';
import { rightsSummary } from './publication-policy.js';
type Selection=ReturnType<typeof publicationFor>;
const link=(route:string,label:string,base:string)=>`<a href="${esc(withBase(route.split('#')[0],base)+(route.includes('#')?'#'+route.split('#')[1]:''))}">${esc(label)}</a>`;
export function renderDownloadTools(s:Selection,e:Entry,base='/') {
  if(!s.manifest.exportIds.includes(e.id))return '';
  const raw=e.sourceRefs.filter(key=>s.manifest.sourceDownloadKeys.includes(key));
  return `<aside class="download-tools"><h2>Take this reading with you</h2><p>${link(exportPath(e.id),'Explanatory Markdown',base)} · ${link(e.route+'#main','Printable view (use browser Print)',base)}</p><p class="reading-note">${s.manifest.mode==='preview'?'Private draft exports; publication approval pending.':'Selected publication export.'} Original downloads preserve raw bytes; explanatory exports apply the disclosed display adapters.</p>${raw.length?`<details><summary>Original sources and provenance</summary><ul>${raw.map(key=>{const source=s.corpus.sources.get(key)!;return `<li>${link(rawPath(key),source.path.split('/').pop()!,base)} — ${esc(source.edition)}; source date ${esc(source.date ?? 'not supplied')}; SHA-256 <code>${source.sha256}</code></li>`;}).join('')}</ul></details>`:''}</aside>`;
}
function group(e:Entry) {
  if(['superseded','withdrawn'].includes(e.publicationState))return 'Historical Sources';
  if(e.audience==='general')return 'Start';
  if(e.kind==='mathematics' || e.kind==='derivation')return 'Mathematics / Results';
  if(['research-status','open-problems','open-problem','evidence','falsification','prediction','conjecture'].includes(e.kind))return 'Research Questions';
  return 'Framework';
}
export function renderLibrary(s:Selection,base='/') {
  const entries=s.entries.filter(e=>!['DOC-HOME','DOC-LIBRARY'].includes(e.id));
  return `<section class="prose"><h2>Document library</h2><p>Reading links, edition and status come from the publication manifest. Original source dates are reported only when supplied. ${link('/cite/','Release and citation details',base)}</p>${['Start','Framework','Mathematics / Results','Research Questions','Historical Sources'].map(name=>`<section><h3>${name}</h3>${entries.some(e=>group(e)===name)?`<ul class="library-list">${entries.filter(e=>group(e)===name).map(e=>`<li><h4>${link(e.route,e.title,base)}</h4><p>${esc(e.audience==='general'?'General audience':'Technical audience')} · ${esc(e.publicationState)} · ${esc(reviewLabel(s.corpus,e.id))}</p><p>Edition: ${esc(e.researchEdition)} · revision ${e.revision} · updated ${e.updatedAt}${e.publishedAt?` · published ${e.publishedAt}`:' · unpublished'}</p><p>${link(e.route+'#main','Printable reading',base)}${s.manifest.exportIds.includes(e.id)?` · ${link(exportPath(e.id),'Explanatory Markdown',base)}`:''}${e.sourceBinding && s.manifest.sourceDownloadKeys.includes(e.sourceBinding.sourceKey)?` · ${link(rawPath(e.sourceBinding.sourceKey),'Original source (exact bytes)',base)}`:''}</p></li>`).join('')}</ul>`:'<p>No historical body is selected for distribution. Retained addenda inside current sources remain part of their supplied edition; separate historical calculations are NOT_SELECTED / NOT_RUN.</p>'}</section>`).join('')}</section>`;
}
export function renderArticles(s:Selection,base='/') {
  const articles=s.entries.filter(e=>e.kind==='article' && s.manifest.navigationIds.includes(e.id));
  return `<p>${link('/rss.xml','RSS of published articles',base)}. Private drafts have no publication date and are excluded from RSS.</p><ul class="library-list">${articles.map(e=>`<li><h2>${link(e.route,e.title,base)}</h2><p>${esc(e.description)}</p><p>${esc(e.publicationState)} · updated ${e.updatedAt}${e.publishedAt?` · published ${e.publishedAt}`:' · unpublished; displayed author approval pending'}</p></li>`).join('')}</ul>`;
}
export function renderHistory(_s:Selection,base='/') {
  return `<section class="prose"><h2>Website presentation history</h2><p>Separate from the source's adopted research changes: 3 October — introduction, examples and concept journey (M2); 4 October — current technical documents, evidence and status readings (M3); 4 October — explanatory articles, document library, generated exports and citation preview (M4; bounded private acceptance); 4 October — contribution forms, identity/rights displays, dependency notices and disabled owner-controlled publication flow (M5 implementation). These do not advance the research edition.</p><p>${link('/changes/source-history/','Read the supplied research changelog',base)} · ${link('/cite/','Inspect this build’s release identity',base)}</p></section>`;
}
export function renderSourceBacklinks(s:Selection,base='/') {
  return `<section class="prose"><h2>Project source backlinks</h2>${[...s.corpus.sources.values()].filter(source=>s.entries.some(e=>e.sourceRefs.includes(source.key))).map(source=>`<section><h3>${esc(source.path.split('/').pop()!)}</h3><p>${esc(source.edition)} · ${source.declaredCurrent?'Current supplied source':'Historical source'} · source date ${esc(source.date ?? 'not supplied')}</p><p>Readings: ${s.entries.filter(e=>e.sourceRefs.includes(source.key)).map(e=>link(e.route,e.title,base)).join(' · ')}</p>${s.manifest.sourceDownloadKeys.includes(source.key)?`<p>${link(rawPath(source.key),'Original bytes',base)} · SHA-256 <code>${source.sha256}</code></p>`:''}</section>`).join('')}</section>`;
}
export function renderCite(s:Selection,config:SiteConfig) {
  const credit=publicationCredit(),assets=publicationAssets(s,config),i=assets.identity,gates=citationGates(credit);
  return `<section class="prose"><h2>Citation preview</h2><p>${esc(credit.title)}. Research edition: ${esc(i.researchEdition)}. Website release: ${esc(i.websiteRelease)} (${i.releaseAt.slice(0,10)}). Public credit: ${esc(credit.approvedCredit?.name ?? 'decision pending')}. Permanent URL: ${esc(credit.permanentUrl ?? 'decision pending')}. ${credit.doi?`DOI: ${esc(credit.doi)}.`:'No project DOI supplied.'}</p><h2>Exact build and release identity</h2><dl><dt>Source commit</dt><dd><code>${i.sourceCommit ?? 'unavailable'}</code></dd><dt>Workspace inputs</dt><dd>${i.workspaceDirty?'Dirty; the commit alone does not describe this build.':'Clean.'} SHA-256 <code>${i.workspaceInputsSha256}</code></dd><dt>Document manifest</dt><dd><code>${i.documentManifestSha256}</code></dd><dt>Website code version</dt><dd>${esc(i.websiteCodeVersion)}</dd></dl><p>Research edition and website release identify different changes. ${link('/downloads/release.json','Download release metadata',config.basePath)}.</p><h2>Article citations</h2><ul>${s.entries.filter(e=>e.kind==='article' && s.manifest.navigationIds.includes(e.id)).map(e=>`<li>${esc(e.title)}. Revision ${e.revision}; updated ${e.updatedAt}; ${e.publishedAt?`published ${e.publishedAt}`:'unpublished private draft'}. ${esc(credit.approvedCredit?.name ?? 'Author approval pending')}. ${link(e.route,'Read article',config.basePath)}. Preview address: <code>${esc(canonicalURL(e.route,config))}</code>.</li>`).join('')}</ul><h2>Downloads and remaining gates</h2><p>${link(assets.zipPath,s.manifest.mode==='preview'?'Private preview publication ZIP':'Selected publication ZIP',config.basePath)} · ${link('/downloads/SHA256SUMS','SHA-256 file manifest',config.basePath)}. This partial selection is not the complete RRG_CURRENT package.</p><p>${esc(rightsSummary(credit))}</p><p>CITATION.cff: ${gates.length?`inactive — ${gates.map(esc).join(', ')}`:link('/downloads/CITATION.cff','Download',config.basePath)}. Actual approved distribution also requires published entries, exact source-fidelity decisions, per-entry rights and a named authorized target. No evidence/history is approved for inclusion. All current entries remain private drafts; qualification and public release remain gated.</p><p>Reserved .invalid addresses are private build placeholders. No permanent URL or source permalink is invented; dirty content cannot be cited as though it were the exact clean commit.</p></section>`;
}
