// Explicit follow-up decision after reading the complete minimal concept entry.
import { readFileSync,writeFileSync } from 'node:fs';
import assert from 'node:assert/strict';
import { loadCanonicalCorpus,reviewState,reviewFingerprint,semanticDigest,renderEntrySync,dependencyClosure } from '../../../../src/lib/content.js';
import { sha256,stableJSON } from '../../../../src/lib/identity.js';
const folder='docs/evidence/m1/scientific-review';
const corpus=loadCanonicalCorpus(),id='DOC-CONCEPT-GEOMETRY',entry=corpus.entries.get(id)!;
assert.equal(reviewState(corpus,id),'pending');
assert.equal(corpus.reviews.length,17);
assert.equal(entry.revision,2);
assert.deepEqual(entry.dependsOn,['UT-D01','UT-D02','UT-D03']);
assert.ok(entry.body.includes('view="plainLanguage"'));
for(const dependency of entry.dependsOn) assert.equal(reviewState(corpus,dependency),'accepted');
assert.deepEqual(entry.bibRefs,[]);
const previousReviews=readFileSync('research/publication/reviews.yaml','utf8');
const prior=JSON.parse(previousReviews);
for(const review of prior) assert.equal(reviewFingerprint(corpus,review.entryId),review.fingerprint);
const rationale='The complete minimal consumer contains only three headings and the exact independently accepted D01/D02/D03 explanations. Its neutral description/scope and draft/non-empirical metadata now agree with that content. Accept its exact explanatory representation, not a scientific theorem or public authorization.';
const report=JSON.parse(readFileSync(`${folder}/review-decisions.json`,'utf8'));
const decision=report.decisions.find((d:any)=>d.entryId===id);
assert.equal(decision.outcome,'pending');
Object.assign(decision,{outcome:'accepted',rationale,acceptedScope:'Exact minimal concept explanation of the three accepted definitions; no universal claim, authorial approval or publication permission.',semanticDigest:semanticDigest(entry),ownRead:{sourceBinding:null,statement:null,plainLanguage:entry.plainLanguage,description:entry.description,scope:entry.scope,limits:entry.limits,evidenceState:entry.evidenceState,publicationState:entry.publicationState,body:entry.body,assumptions:entry.assumptions,dependsOn:entry.dependsOn,bibRefs:entry.bibRefs},dependencies:dependencyClosure(corpus,id).map(id=>({id,semanticDigest:semanticDigest(corpus.entries.get(id)!)})),renderedBodySha256:sha256(renderEntrySync(corpus,entry)),independentlyComputedFingerprint:reviewFingerprint(corpus,id)});
report.followup='Requested quality recheck: one explicit minimal concept acceptance after neutral status-metadata repair. Initial decision report preserved in pre-recheck. Seventeen existing approval fingerprints and meanings unchanged.';
report.readoutSha256=sha256(readFileSync(`${folder}/source-readout.md`));
report.accessLedgerSha256=sha256(readFileSync(`${folder}/access-ledger.json`));
writeFileSync(`${folder}/review-decisions.json`,JSON.stringify(report,null,2)+'\n');
prior.push({entryId:id,fingerprint:decision.independentlyComputedFingerprint,reviewerKind:'agent',reviewedAt:'2026-10-01',outcome:'accepted',evidenceRef:`${folder}/review-decisions.json#${id}`});
assert.equal(stableJSON(prior.slice(0,17)),stableJSON(JSON.parse(previousReviews)));
writeFileSync('research/publication/reviews.yaml',JSON.stringify(prior,null,2)+'\n');
assert.equal(reviewState(loadCanonicalCorpus(),id),'accepted');
assert.equal(loadCanonicalCorpus().admission.currentSourceQualified,false);
console.log('Explicit minimal concept review recorded; original 17 approvals unchanged; 18 representation acceptances, 16 pending exact reviews.');
