import { readFileSync,writeFileSync } from 'node:fs';
import assert from 'node:assert/strict';
import { loadCanonicalCorpus,reviewState,reviewFingerprint,semanticDigest,renderEntrySync } from '../../../../src/lib/content.js';
import { sha256 } from '../../../../src/lib/identity.js';
const folder='docs/evidence/m1/scientific-review';
const corpus=loadCanonicalCorpus(),id='DOC-CONCEPT-GEOMETRY',entry=corpus.entries.get(id)!;
assert.equal(entry.updatedAt,'2026-10-02');
assert.equal(reviewState(corpus,id),'stale');
const reviews=JSON.parse(readFileSync('research/publication/reviews.yaml','utf8'));
for(const review of reviews.filter((r:any)=>r.entryId!==id)) assert.equal(reviewState(corpus,review.entryId),'accepted');
const previous=JSON.parse(readFileSync(`${folder}/before-date-reconciliation/research/publication/canonical-documents.yaml`,'utf8')).find((e:any)=>e.id===id);
const current=JSON.parse(readFileSync('research/publication/canonical-documents.yaml','utf8')).find((e:any)=>e.id===id);
assert.deepEqual({...current,updatedAt:previous.updatedAt},previous);
const reviewed=reviews.find((r:any)=>r.entryId===id);
reviewed.reviewedAt='2026-10-02';reviewed.fingerprint=reviewFingerprint(corpus,id);
const report=JSON.parse(readFileSync(`${folder}/review-decisions.json`,'utf8'));
const decision=report.decisions.find((d:any)=>d.entryId===id);
decision.reviewedAt=reviewed.reviewedAt;decision.ownRead.updatedAt=entry.updatedAt;
decision.semanticDigest=semanticDigest(entry);decision.independentlyComputedFingerprint=reviewed.fingerprint;
assert.equal(decision.renderedBodySha256,sha256(renderEntrySync(corpus,entry)));
report.dateReconciliation='Initial source reads began 1 October; concept metadata revision and final exact review completed 2 October UTC. Only the concept dates were reconciled; first 17 reviews unchanged. No body/explanation changed.';
writeFileSync(`${folder}/review-decisions.json`,JSON.stringify(report,null,2)+'\n');
writeFileSync('research/publication/reviews.yaml',JSON.stringify(reviews,null,2)+'\n');
assert.equal(reviewState(loadCanonicalCorpus(),id),'accepted');
console.log('Concept update/review dates reconciled to 2 October; 17 earlier reviews unchanged; final reviewed body unchanged.');
