import assert from 'node:assert/strict';
import {readFileSync,writeFileSync} from 'node:fs';
import {auditOutput} from '../../../../scripts/audit-output.js';
import {buildInputs} from '../../../../src/lib/build-identity.js';
const folder='docs/evidence/m1/qf1214-separate-review';
const json=(path:string)=>JSON.parse(readFileSync(path,'utf8'));
const engineering=json(`${folder}/independent-engineering.json`);
assert.equal(engineering.status,'PASS');
assert.ok(engineering.outcomes.every((r:any)=>r.expected===r.outcome && r.untouchedCopy==='PASS'));
const verification=json(`${folder}/verification.json`);
assert.equal(verification.status,'PASS');assert.equal(verification.receipts.length,11);
assert.ok(verification.receipts.every((r:any)=>r.exitCode===0));assert.deepEqual(verification.notRun,[]);
const log=readFileSync(`${folder}/verification.log`,'utf8').replace(/\x1b\[[0-9;]*m/g,'');
const cases=[...log.matchAll(/^✔ (.+?) \([\d.]+ms\)$/gm)].map(m=>m[1]);
assert.equal(cases.length,82);assert.equal(new Set(cases).size,82);
const predecessor=readFileSync('docs/evidence/m1/audit-normalization-recheck/verification.log','utf8').replace(/\x1b\[[0-9;]*m/g,'');
const previousCases=[...predecessor.matchAll(/^✔ (.+?) \([\d.]+ms\)$/gm)].map(m=>m[1]);
assert.deepEqual([...cases].sort(),previousCases.sort());
assert.match(log,/0 errors/);assert.match(log,/0 warnings/);assert.match(log,/0 hints/);
const artifacts=['root','subpath'].map(suffix=>{
  const directory=`dist/m1-qf1214-separate-review/preview-${suffix}`,audit=auditOutput(directory);
  assert.deepEqual(audit,json(`${folder}/${suffix}-artifact.json`));
  const old=json(`docs/evidence/m1/audit-normalization-recheck/${suffix}-artifact.json`);
  assert.deepEqual(audit.files.filter(f=>f.path!=='build-info.json'),old.files.filter((f:any)=>f.path!=='build-info.json'));
  const browser=json(`${folder}/${suffix}-browser.json`);
  assert.equal(browser.stats.expected,7);
  for(const key of ['unexpected','flaky','skipped'])assert.equal(browser.stats[key],0);
  return {directory,artifactSha256:audit.artifactSha256,files:audit.files.length,html:audit.files.filter(f=>f.path.endsWith('.html')).length,chromium:7,postBrowserAudit:'PASS',nonBuildInfoFiles:'100 unchanged'};
});
const semantics=json(`${folder}/browser-semantics.json`);
assert.equal(semantics.results.length,6);
assert.ok(semantics.results.find((r:any)=>r.name==='svg-stylesheet-pi').remoteRequests.includes('https://remote.invalid/theme.css'));
for(const attribute of ['fill','cursor'])assert.ok(semantics.results.find((r:any)=>r.name===`inline-svg-${attribute}`).remoteRequests.length>0);
assert.deepEqual(buildInputs(),engineering.productionInputs);
const result={status:'PASS',reviewedHead:engineering.reviewedHead,productionInputs:engineering.productionInputs,renderer:engineering.renderer,contracts:82,commands:11,chromium:14,browserSemanticChecks:6,negativeControls:engineering.negativeControls,positiveControls:engineering.positiveControls,artifacts,retained:engineering.retained,representations:engineering.representations,reviewStates:engineering.reviewStates,currentSourceQualified:true,newFidelityDecisions:'NONE',productionOrTestRepairs:'NONE',decision:'ACCEPTED: demonstrated unchanged QF-12–14 static resource audit scope',m1:'ACCEPTED',m2:'NOT_STARTED',scientificAdjudication:'DEFERRED',publicActions:'NOT_RUN',humanComprehension:'NOT_TESTED',scopeLimit:'No exhaustive CSS/browser sandbox, arbitrary content/visibility, human/a11y/live/public release acceptance'};
writeFileSync(`${folder}/final-checks.json`,JSON.stringify(result,null,2)+'\n');
console.log(JSON.stringify({...result,representations:result.representations.length,retained:result.retained.length}));
